### ISSUE TITLE
How to indicate block end?

### ISSUE THREAD

**Issue by lesyk-lesyk** [UX-and-I/storybook-design-token#105]
Imagine, I have the next css styles (with 2 presenters - `Color` and `FontSize`):

```css
:root {
  /**
    * @tokens Colors
    * @presenter Color
    */
  --b100: hsl(240, 100%, 90%);
  --b200: hsl(240, 100%, 80%);
  --b300: hsl(240, 100%, 70%);

  /* Problem: Next two variables will be joined to Colors tokens */
  --logo-height: 2rem;
  --logo-margin: var(--sidebar-margin-left);

  /**
    * @tokens Font Sizes
    * @presenter FontSize
    */
  --font-size-s: 0.75rem;
  --font-size-m: 0.875rem;
  --font-size-l: 1rem;
}
```

Page `design.mdx`:
```mdx
import { Meta } from '@storybook/addon-docs';
import { DesignTokenDocBlock } from 'storybook-design-token/dist/doc-blocks';

<Meta title="Design Tokens" />

# Design Tokens

<br />

## Colors

<DesignTokenDocBlock categoryName="Colors" />

## Font Sizes

<DesignTokenDocBlock categoryName="Font Sizes" />
```

And the result page:

![image](https://user-images.githubusercontent.com/16646570/168294358-03aa19fd-9f47-4ec9-9541-d092859841eb.png)

------
Is there a way to indicate the end of the colors variables block? E.g with some annotation comment like `/* @end Colors */`
```css
:root {
  /**
    * @tokens Colors
    * @presenter Color
    */
  --b100: hsl(240, 100%, 90%);
  --b200: hsl(240, 100%, 80%);
  --b300: hsl(240, 100%, 70%);
  /* @end Colors */

  /* Next styles will not joined to group above */
  --logo-height: 2rem;
  --logo-margin: var(--sidebar-margin-left);

....
}
```
