### ISSUE TITLE
Unstable variables preview

### ISSUE THREAD

**Issue by lesyk-lesyk** [UX-and-I/storybook-design-token#106]
I have CSS like this:

```css
{
  /**
  * @tokens Spacings
  * @presenter Spacing
  */
  --spacing-unit: 5px;
  --spacing-horizontal: calc(var(--spacing-unit) * 8);
  --spacing-vertical: calc(var(--spacing-unit) * 4);
}
```

When I run locally in dev mode - everything looks good (left side on screenshot)/
When I build and start the local static server (or deploy to chromatic.com) - examples look broken (right side on screenshot)

![image](https://user-images.githubusercontent.com/16646570/168302712-d0353a94-c076-4820-a0ac-e6eb0ef1c433.png)

Sometimes when I refresh the page - examples become normal, but most of the time my examples look broken.

![image](https://user-images.githubusercontent.com/16646570/168306845-3b2a37c2-e69c-4cee-8534-d7edbe6a7471.png)

**Versions:**
- `"storybook-design-token": "^2.1.0"`
- `"@storybook/react": "^6.4.22"`
- `"@storybook/builder-webpack5": "^6.4.22"`
