### ISSUE TITLE
Design tokens are not displayed in story-book if there is only a category name.

### ISSUE THREAD

**Issue by SmoliyY** [UX-and-I/storybook-design-token#121]
## Version
`storybook-design-token`: `2.6.0`

## Steps to Reproduce
Create basic storybook with next `design-tokens`. Example: 

```css
:root {
  /**
  * @tokens Animations
  * @presenter Animation
  */

  --animation-rotate: rotate 1.2s infinite cubic-bezier(0.55, 0, 0.1, 1);

  /**
  * @tokens Colors
  * @presenter Color
  */

  --b100: hsl(240, 100%, 90%); /* Token Description Example  @presenter Color */
  --b200: hsl(240, 100%, 80%);
  --b300: hsl(240, 100%, 70%);

  /**
  * @tokens Others
  */
  --border-normal: 3px dashed red; /* Token Description Example @presenter BorderRadius */
}

```

## Current Behavior

`Animations` and `Colors` sections displayed as expected, but not `Others`.
<img width="1617" alt="Screenshot 2022-08-17 at 18 49 43" src="https://user-images.githubusercontent.com/52038205/185185452-437a194b-cde5-4256-aa35-56f3e0b11f41.png">

## Expected Behavior

`Others` section should be displayed with appropriate `@presenter BorderRadius` preview.
