### ISSUE TITLE
Can't parse tokens if there is only one @tokens comment in a file

### ISSUE THREAD

**Issue by ilyamore88** [UX-and-I/storybook-design-token#131]
### File for example:
```css
.hds-root-colors-dark {
  /**
  * @tokens Colors Dark
  * @presenter Color
  */
  --color-bg-primary: #2f3341;
  --color-bg-secondary: #252732;
  --color-bg-tertiary: #1b1d26;
  --color-accent-brand: #4979e4;
  --color-bg-main-transparent: rgba(36, 39, 50, 0);
  --color-bg-placeholder: #505b74;
}
```

### Output in design-tokens.source.json:
```text
{"cssTokens":{"categories":[{"name":"Colors Dark","presenter":"Color","range":{"from":{"column":3,"line":2},"to":{"column":3,"line":2}},"source":"/Users/ilyamore88/Documents/codex-team/hawk.garage.react/src/commons/themes/root-colors-dark.css","tokens":[]},{"name":"Colors Light", ...
```

### How did I fix it:
I've added `/* @tokens End */` at the end of my file:
```css
.hds-root-colors-dark {
  /**
  * @tokens Colors Dark
  * @presenter Color
  */
  --color-bg-primary: #2f3341;
  --color-bg-secondary: #252732;
  --color-bg-tertiary: #1b1d26;
  --color-accent-brand: #4979e4;
  --color-bg-main-transparent: rgba(36, 39, 50, 0);
  --color-bg-placeholder: #505b74;
  /* @tokens End */
}
```

Output in design-tokens.source.json:
```text
{"cssTokens":{"categories":[{"name":"Colors Dark","presenter":"Color","range":{"from":{"column":3,"line":2},"to":{"column":34,"line":11}},"source":"/Users/ilyamore88/Documents/codex-team/hawk.garage.react/src/commons/themes/root-colors-dark.css","tokens":[{"isAlias":false,"name":"--color-bg-primary","presenter":"Color","rawValue":"#2f3341","sourceType":"CSS","value":"#2f3341"},{"isAlias":false,"name":"--color-bg-secondary","presenter":"Color","rawValue":"#252732","sourceType":"CSS","value":"#252732"},{"isAlias":false,"name":"--color-bg-tertiary","presenter":"Color","rawValue":"#1b1d26","sourceType":"CSS","value":"#1b1d26"},{"isAlias":false,"name":"--color-accent-brand","presenter":"Color","rawValue":"#4979e4","sourceType":"CSS","value":"#4979e4"},{"isAlias":false,"name":"--color-bg-main-transparent","presenter":"Color","rawValue":"rgba(36, 39, 50, 0)","sourceType":"CSS","value":"rgba(36, 39, 50, 0)"},{"isAlias":false,"name":"--color-bg-placeholder","presenter":"Color","rawValue":"#505b74","sourceType":"CSS","value":"#505b74"}]},{"name":"Colors Light", ...
```

> The version is 2.7.1
