### ISSUE TITLE
Feature Request: Color Scheme support

### ISSUE THREAD

**Issue by gossi** [UX-and-I/storybook-design-token#14]
I do have themes, that I want to swap in storybook and these themes do have different color schemes. Here is what I might look like:

```css
:root {
	--background: gray;
}

@media (prefers-color-scheme: light) {
	:root {
		--background: white;
	}
}

@media (prefers-color-scheme: dark) {
	:root {
		--background: #333;
	}
}

.themeName-dark {
	--background: #333;
}
```

Color schemes can come in with media query support or custom classes.

Is there a way to make them been listed?
