### ISSUE TITLE
Feature Request: ability to provide a custom function to create Token

### ISSUE THREAD

**Issue by acherkashin** [UX-and-I/storybook-design-token#93]
Hi! First of all, thank you for this great storybook addon. I'm looking forward to integrating it for my work project. But currently it is very hard to display my design tokens with this addon due to the following reasons:

# 1. Svg

I need to modify every svg  file to add either `id` or `data-token-name`. It makes it hard to use the addon for any existing project. 

## Possible solution

To make it easier to use the addon for existing projects we could use `file path` or `file name` to specify the token name. In this case, it will not be necessary to go and modify all existing `svg` files. 

It should be one-line change so I could create a pull-request if you approve this change.

# 2. Less variables

The approach with using `@tokens` and `@presenters` works well for the global variables.
```
/**
  * @tokens Colors
  * @presenter Color
  */
```

However, we use a kind of a "component approach" to specify colors and icons for every component.  In this case, we need to specify `@tokens` and `@presenter` for every like what makes it almost impossible to use the addon. 

```less
@chat-user-icon: url('@{images-icons-path}/chat-icon-user.svg');
@chat-close-icon: @icon-cross-dark;
@chat-support-icon: url('@{images-icons-path}/chat-icon-support.svg');
@chat-header-background: @color-secondary-light4;
@chat-minimize-background: @color-secondary-dark4;
@chat-panel-bordercolor: @color-secondary-dark5;\
@chat-panel-fontweight: @font-weight-bold;
```

## Possible solution

I guess, this could be solved if we could specify custom function which returns `Token` for css/less variable, or even better function `postProcessToken` where we could modify only needed fields of the token. I'm not sure if it is possible, but we could specify this custom function in `.storybook/main.js` file. 

In my case it is easy to determine `@presenter` based on token name, if variable name ends with`background` or `color`, `Color` presenter should be used, the same logic for variable which ends with `fontweight`. So, the function would look like:

```
({variableName}) => {
  if (variableName.endsWith('background')) {
    return {
      // other Token properties
      presenter: `Color`
    };
  } else if(variableName.endsWith('fontweight')) {
    return {
      // other Token properties
      presenter: 'FontWeight',
    };
  }
}
``` 

This approach could solve issue with svg as well, as we could provide custom function and use filename or path there to specify token name.
