### ISSUE TITLE
Feature request: override design token value

### ISSUE THREAD

**Issue by edoardocavazza** [UX-and-I/storybook-design-token#94]
Consider the case:

**_base.css**
```css
/**
 * @tokens Colors
 * @presenter Color
 */
:root {
    --color-primary: black;
}
```

**index.css**
```css
@import './_base.css';

/**
 * @tokens Colors
 * @presenter Color
 */
:root {
    --color-primary: orange;
}
```

At the moment, the addon collects two entries, showing the variable twice in the Storybook.

We use to extend a primer css library in order to make our styles consistent across projects. I know it may not be a common case, but it makes sense to me that variable values are merged by the addon. Would you consider this change?

Thanks!
